- name: copy Dir
  gather_facts: No
  hosts: group_minecraft
  vars:
    user_name: centos
  tasks:  
    - name: Push dir
      copy: src=/home/avtru/ansible_wf/minecraft/ dest=/home/centos/minecraft
    - name: chmod+x   
      file:
        dest:/home/centos/minecraft/logs/       
      mode: a+x
